name: Deploy site and lambda
on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-1
  S3_BUCKET: hughkirkpatrick.net
  CLOUDFRONT_DISTRIBUTION_ID: E3LXKXB20Q7P70
  HF_USERNAME: Singular-Bean
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  SPACE_NAME: sequence-sim

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v4
          with:
            fetch-depth: 0
            lfs: true

      -   name: Init git-lfs
          run: git lfs install

      -   uses: actions/setup-node@v4
          with:
            node-version: latest

      -   uses: pnpm/action-setup@v3
          with:
            version: 10

      -   name: Install packages
          run: pnpm install --frozen-lockfile

      -   name: Build site
          run: pnpm run build site

      -   name: Sync site to S3
          run: |
            aws s3 sync ./site/dist s3://$S3_BUCKET/sequence-sim

      -   name: Invalidate CloudFront Cache
          run: |
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

      - name: Push to Hugging Face Space
        run: |
          git remote add hf "https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME"
          git push hf HEAD:main --force
